### ISSUE TITLE
Not all netCDF files have the long_name property in their variables

### ISSUE THREAD

**Issue by orioltinto** [Josue-Martinez-Moreno/blendernc#9]
In the **BlenderncEngine**  method **netcdf_var** (line 51 of **core.py**):
`var_names = [(variable[ii], variable[ii], self.dataset[variable[ii]].long_name, "DISK_DRIVE", ii) for ii in range(len(variable))]`

it is trying to access the variable *long_name* which happens to be missing in some netCDF files.

I would suggest to use simply **.name** that I believe that will be always present.

If the choice was a personal preference it is possible to check first whether **.long_name** exist and if it is not the case use **.name** instead.

**Comment by josuemtzmo** [comment]
This issue has been addressed in the merged pull request #10
